# Generated by Django 6.0.2 on 2026-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
