# Generated by Django 6.0.2 on 2026-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
